apiVersion: v1
name: spark-history-server
version: 1.4.3
appVersion: 2.4.0
description: A Helm chart for Spark History Server
home: https://spark.apache.org
sources:
  - https://github.com/apache/spark
keywords:
- spark
- history-server
